cpdef double trace(double[:, :] m, int n)
cpdef double vectors_dot_prod(double[:] x, double[:] y, int n)
cpdef double[:] matrix_vector_mult(double[:, :] mat, double[:] vec, int rows, int cols)
cpdef double[:, :] matrix_mult(double[:, :] m1, double[:, :] m2, int rows, int cols, int n)
cpdef double _2x2_det(double[:, :] m)
cpdef double _3x3_det(double[:, :] m)
cpdef double[:, :] _3x3_inv(double[:, :] m)
cpdef bint check_orthogonal(double[:, :] m, int rows, int cols, double tol)
cpdef double[:] decomp(double[:, :] m)
